name = "miniflare-typescript-esbuild-jest"
main = "dist/index.mjs"
compatibility_date = "2022-05-28"
compatibility_flags = []

[[migrations]]
tag = "v1"
new_classes = ["Types"]

[build]
command = "node build.js"

[vars]
API_HOST = "http://example.com"
INDEXES = ["article", "video"]

[miniflare]
kv_persist = true
cache_persist = true
durable_objects_persist = true
